<header>
  <h1 class="nav-title">
    <a href="javascript:;">
      <img src="/assets/images/logo.svg" alt="플그림" />
      <span>2022.10</span>
    </a>
  </h1>
  <ul class="nav">
    <li class="on">
      <span>Guide</span>
      <ul class="nav-list">
        <li class="items">
          <a href="index.html">기본정책</a>
        </li>
        <li class="items">
          <a href="standard.html">표준규칙</a>
        </li>
        <li class="items">
          <a href="rule.html">코드규칙</a>
        </li>
        <li class="items">
          <a href="name.html">네임규칙</a>
        </li>
      </ul>
    </li>
    <li>
      <span>Script</span>
    </li>
    </li>
  </ul>
</header>
